version: "3"
services:
  app:
    build: .
    depends_on:
      - mongo
      - postgres
    ports:
      - 80:80
  mongo:
    image: mongo:4.0
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
    volumes:
      - ./data/mongo:/data/db
      - ./data/logs:/data/logs
    ports:
      - "27017:27017"
    command: mongod --smallfiles
  postgres:
      image: postgres:14.0
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - ./data/postgresql:/var/lib/postgresql/data
      ports:
        - "5432:5432"